export const reviews = [
    {
      id: 1,
      name: "John Doe",
      image: "/review1.jpg",
      rating: 5,
      comment: "This platform transformed my financial future! The referral program is amazing and the returns are steady and reliable.",
    },
    {
      id: 2,
      name: "Jane Smith",
      image: "/review2.jpg",
      rating: 4,
      comment: "I love the transparency and the user-friendly interface. The support team is always responsive and helpful.",
    },
    {
      id: 3,
      name: "Samuel Johnson",
      image: "/review3.jpg",
      rating: 4,
      comment: "A fantastic investment platform. The daily returns are impressive and I enjoy referring my friends.",
    },
    {
      id: 4,
      name: "Emily Davis",
      image: "/review4.jpg",
      rating: 5,
      comment: "Absolutely outstanding service! I've never seen such commitment to customer success before.",
    },
    {
      id: 5,
      name: "Michael Brown",
      image: "/review5.jpg",
      rating: 4,
      comment: "The system is intuitive and the investment options are diverse. I’m earning great returns consistently.",
    },
    {
      id: 6,
      name: "Olivia Wilson",
      image: "/review6.jpg",
      rating: 4,
      comment: "Reliable and innovative! The referral rewards add a great bonus to the daily returns.",
    },
    {
      id: 7,
      name: "Liam Martinez",
      image: "/review7.jpg",
      rating: 5,
      comment: "Truly impressed with the seamless experience and high level of security offered.",
    },
    {
      id: 8,
      name: "Sophia Garcia",
      image: "/review8.jpg",
      rating: 4,
      comment: "The platform is user-friendly, and the investment process is straightforward, making it accessible for everyone.",
    },
    {
      id: 9,
      name: "Noah Rodriguez",
      image: "/review9.jpg",
      rating: 4,
      comment: "Steady returns and excellent customer support—a win-win for any investor.",
    },
    {
      id: 10,
      name: "Ava Lee",
      image: "/review10.jpg",
      rating: 5,
      comment: "The investment plans are flexible and the referral bonuses are the icing on the cake!",
    },
    {
      id: 11,
      name: "Ethan Clark",
      image: "/review11.jpg",
      rating: 4,
      comment: "A trustworthy platform with an innovative approach to investing and earning passive income.",
    },
    {
      id: 12,
      name: "Isabella Lewis",
      image: "/review12.jpg",
      rating: 4,
      comment: "The interface is clean and navigating through the investment options is a breeze.",
    },
    {
      id: 13,
      name: "Mason Walker",
      image: "/review13.jpg",
      rating: 5,
      comment: "Highly recommended! The potential for growth and the support from the team are unparalleled.",
    },
    {
      id: 14,
      name: "Mia Hall",
      image: "/review14.jpg",
      rating: 4,
      comment: "I've been a member for a while, and the returns have consistently exceeded my expectations.",
    },
    {
      id: 15,
      name: "Logan Allen",
      image: "/review15.jpg",
      rating: 4,
      comment: "A robust platform that offers both security and excellent growth opportunities.",
    },
    {
      id: 16,
      name: "Charlotte Young",
      image: "/review16.jpg",
      rating: 5,
      comment: "The customer service is exceptional and the referral program is a great incentive.",
    },
    {
      id: 17,
      name: "Lucas Hernandez",
      image: "/review17.jpg",
      rating: 4,
      comment: "I appreciate the transparency and consistent performance. It’s a reliable choice for smart investing.",
    },
    {
      id: 18,
      name: "Amelia King",
      image: "/review18.jpg",
      rating: 4,
      comment: "The platform is well-designed and the investment options cater to a wide range of needs.",
    },
    {
      id: 19,
      name: "Oliver Scott",
      image: "/review19.jpg",
      rating: 5,
      comment: "This is not just an investment platform; it's a community that genuinely cares about your success.",
    },
    {
      id: 20,
      name: "Evelyn Adams",
      image: "/review20.jpg",
      rating: 4,
      comment: "I love how easy it is to navigate and track my investments. The referral system is an added bonus.",
    },
  ];  